config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  devise_scope :user do 
    authenticated :user do
      root 'pages#dashboard', as: :user_root
      resources 'accounts', except: [:destroy] do
        resources 'incomes', except: [:index]
        resources 'expenses', except: [:index]
        resources 'transfers', except: [:index, :destroy]
      end
      resources 'categories', except: [:destroy]
    end
  end
  get '/service-worker.js' => "service_worker#service_worker"
  get '/manifest.json' => "service_worker#manifest"
  root 'devise/sessions#new'
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :incomes
    has_many :expenses
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]
    before_action :category_icons, only: [:new, :create, :edit, :update]
    def index
        @categories = Category.all
    end

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            redirect_to categories_path
        else
            render :new
        end
    end

    def edit

    end

    def update
        if @category.update(category_params)
            redirect_to categories_path
        else
            render :edit
        end
    end

    private
        def set_category
            @category = Category.find(params[:id])
        end
        def category_params
            params.require(:category).permit!
        end
        def category_icons 
            @icon_names = [
                'ambulance',
                'h square',
                'heart',
                'heart outline',
                'heartbeat',
                'hospital',
                'medkit',
                'plus square',
                'plus square outline',
                'user md',
                'wheelchair',
                'dollar sign',
                'euro sign',
                'lira sign',
                'pound sign',
                'ruble sign',
                'rupee sign',
                'shekel sign',
                'won sign',
                'yen sign',
                'clipboard list',
                'shipping fast',
                'truck',
                'ambulance',
                'anchor',
                'balance scale',
                'bath',
                'bed',
                'beer',
                'bell',
                'bell outline',
                'bell slash',
                'bell slash outline',
                'bicycle',
                'binoculars',
                'birthday cake',
                'blind',
                'bomb',
                'book',
                'bookmark',
                'bookmark outline',
                'briefcase',
                'building',
                'building outline',
                'car',
                'coffee',
                'crosshairs',
                'dollar sign',
                'eye',
                'fighter jet',
                'fire',
                'fire extinguisher',
                'flag',
                'flag outline',
                'flag checkered',
                'flask',
                'gamepad',
                'gift',
                'globe',
                'graduation cap',
                'h square',
                'heart',
                'heart outline',
                'heartbeat',
                'home',
                'hospital',
                'industry',
                'info',
                'info circle',
                'key',
                'leaf',
                'lemon',
                'life ring',
                'lightbulb',
                'location arrow',
                'low vision',
                'magnet',
                'male',
                'map',
                'map outline',
                'map signs',
                'medkit',
                'motorcycle',
                'music',
                'newspaper',
                'paw',
                'phone',
                'phone square',
                'phone volume',
                'plug',
                'plus',
                'plus square',
                'plus square outline',
                'print',
                'recycle',
                'road',
                'rocket',
                'search',
                'search minus',
                'search plus',
                'ship',
                'shopping bag',
                'shopping basket',
                'shopping cart',
                'shower',
                'street view',
                'subway',
                'suitcase',
                'tag',
                'tags',
                'taxi',
                'ticket alternate',
                'tint',
                'train',
                'tree',
                'trophy',
                'truck',
                'tty',
                'umbrella',
                'university',
                'utensil spoon',
                'wheelchair',
                'wifi',
                'wrench',
                'desktop',
                'download',
                'hdd outline',
                'keyboard',
                'laptop',
                'microchip',
                'mobile',
                'mobile alternate',
                'plug',
                'power off',
                'print',
                'save',
                'server',
                'tablet',
                'tablet alternate',
                'tv',
                'upload',
                'ambulance',
                'first aid',
                'heart',
                'heart outline',
                'heartbeat',
                'hospital',
                'hospital symbol',
                'plus',
                'thermometer',
                'user md',
                'gift',
                'credit card',
                'bus',
                'car',
                'plane',
        ].uniq.sort
        end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category, html: {class: 'ui form'}) do |f| %>
    <div class="field">
        <%= f.input :name, label: 'Category Name' %>
    </div>
    <div class="field">
         <label class="select optional" for="category_icon">Icon</label>
         <div class="ui fluid search selection dropdown">
            <input class="string optional" type="hidden" name="category[icon]" id="category_icon">
            <i class="dropdown icon"></i>
            <div class="default text"></div>
            <div class="menu">
            <% @icon_names.each do |icon| %>
                <div class="item" data-value="<%= icon %>"><i class="<%= icon %> icon"></i> <%=icon %></div>
            <% end %>
            </menu>
         </div>
    </div>
    <br>
    <div class="field">
        <%= f.button :submit, class: 'ui fluid primary button' %>
    </div>
<% end %>

<script>
$(document).on('turbolinks:load', function(){
    $('.search.dropdown').dropdown();
  });
</script>

app/views/categories/edit.html.erb
<h1>Edit <%=@category.name %> Category</h1>

<%= render 'form'%>

app/views/categories/index.html.erb
<br>
<div class="ui six stackable cards">
    <% @categories.each do |category| %>
    <div class="card">
        <div class="content" style="text-align:center;">
            <div class="header" > 
                <%= category.name %>
            </div>
            <div class="meta">
                Category Icon: <%= semantic_icon(category.icon) %>
            </div>
        </div>
        <div class="extra content centered">
            <%= link_to 'Edit', edit_category_path(category), class: 'ui fluid secondary button'%>
        </div>
    </div>
    <% end %>
</div>
<br>
<a href="<%= new_category_path%>" class="fluid ui primary button">Add a Category</a>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form'%>