config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  devise_scope :user do 
    authenticated :user do
      root 'pages#dashboard', as: :user_root
      resources 'accounts', except: [:destroy] do
        resources 'incomes', except: [:index]
        resources 'expenses', except: [:index]
        resources 'transfers', except: [:index, :destroy]
      end
      resources 'categories', except: [:destroy]
    end
  end
  get '/service-worker.js' => "service_worker#service_worker"
  get '/manifest.json' => "service_worker#manifest"
  root 'devise/sessions#new'
end

app/views/layouts/_menu.html.erb
<div class="ui top menu">
    <div class="item menu-item" onclick="$('.ui.sidebar').sidebar('toggle')">
        <%= semantic_icon('bars') %>
        <p>Menu</p>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<a href="<%= root_path %>" class="item">
    <%= semantic_icon('pie graph') %>
    <br>
    Dashboard
</a>

<a href="<%= accounts_path %>" class="item">
    <%= semantic_icon('briefcase') %>
    Accounts
</a>

<a href="<%= categories_path %>" class="item">
    <%= semantic_icon('tasks') %>
    Categories
</a>

<a href="<%= edit_user_registration_path %>" class="item">
    <%= semantic_icon('settings') %>
    User Settings
</a>

<a href="<%= destroy_user_session_path %>" data-method="delete" class="item">
    <%= semantic_icon('sign out alternate') %>
    Log Out
</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finance Manager</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="/manifest.json">
    <meta name="theme-color" content="#fff"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <div class="ui labeled icon sidebar vertical menu">
          <%= render 'layouts/navigation' %>
      </div>
      <div class="pusher">
          <%= render 'layouts/menu' %>
          <div class="ui container">
            <%= yield %>    
          </div>
      </div>
    <% else %>
      <div class="ui container">
        <%= yield %>  
      </div>
    <% end %>
  </body>
</html>