config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  devise_scope :user do 
    authenticated :user do
      root 'pages#dashboard', as: :user_root
      resources 'accounts', except: [:destroy] do
        resources 'incomes', except: [:index]
        resources 'expenses', except: [:index]
        resources 'transfers', except: [:index, :destroy]
      end
      resources 'categories', except: [:destroy]
    end
  end
  get '/service-worker.js' => "service_worker#service_worker"
  get '/manifest.json' => "service_worker#manifest"
  root 'devise/sessions#new'
end

app/models/account.rb
class Account < ApplicationRecord
    belongs_to :user
    has_many :expenses
    has_many :incomes
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    before_action :set_account, only: [:show, :edit, :update, :destroy]
    
    def index
        @accounts = current_user.accounts.all
    end

    def new
        @account = current_user.accounts.new
    end

    def create
        @account = current_user.accounts.new(account_params)
        if @account.save
            redirect_to accounts_path
        else
            render :new
        end
    end

    def show

    end

    def edit

    end

    def update
        if @account.update(account_params)
            redirect_to account_path(@account)
        else
            render :edit
        end
    end

    def destroy
        @account.delete
        redirect_to root_path
    end

    private
        def set_account
            @account = Account.find(params[:id])
        end

        def account_params
            params.require(:account).permit!
        end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account, html: {class: 'ui form'}) do |f| %>
    <div class="field">
        <%= f.input :name %>
    </div>
    <div class="field">
        <%= f.input :balance, label: 'Current Balance' %>
    </div>
    <div class="field">
        <%= f.button :submit, class: 'fluid ui primary button' %>
    </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Edit <%@account.name %></h1>

<%=render 'form' %>

app/views/accounts/index.html.erb
<br>
<div class="ui three stackable cards">
    <% @accounts.each do |account| %>
    <div class="card">
        <div class="content">
            <div class="header"> <%= account.name %></div>
            <div class="meta">
                <%= link_to 'View Account', account_path(account), style: 'color: blue; text-decoration: underline'%><br>
                Current Balance: <%= 'Php %.2f' % account.balance %> <br>
                Transaction Count: <%= account.incomes.count + account.expenses.count %><br>
            </div>
        </div>
        <div class="extra content centered">
            <div class="ui buttons">
                <%= link_to 'Add Expense', new_account_expense_path(account), class: 'ui primary button' %>
                <%= link_to 'Add Income', new_account_income_path(account), class: 'ui green button'%>
                <%= link_to 'Transfer', new_account_transfer_path(account), class: 'ui secondary button'%>
            </div>
        </div>
    </div>
    <% end %>
</div>
<br>
<a href="<%= new_account_path%>" class="fluid ui primary button">Add an Account</a>

app/views/accounts/new.html.erb
<h1>Add a New Account</h1>
<%= render 'form' %>

app/views/accounts/show.html.erb
<%= link_to 'Back', accounts_path %>
<h1><%= @account.name %></h1>
 Current Balance: <%= 'Php %.2f' % @account.balance %>
<br>
<div class="ui buttons">
  <%= link_to 'Add Expense', new_account_expense_path(@account), class: 'ui primary button' %>
  <%= link_to 'Add Income', new_account_income_path(@account), class: 'ui green button'%>
  <%= link_to 'Transfer', new_account_transfer_path(@account), class: 'ui secondary button'%>
  <%= link_to "Edit Account", edit_account_path(@account), class: 'ui primary button' %>
</div>

<div class="ui top attached tabular menu active">
  <a class="active item" data-tab="expenses">
    Expenses
  </a>
  <a class="item" data-tab="income">
    Income
  </a>
</div>

<div class="ui bottom attached active tab segment" data-tab="expenses">
  <div class="ui feed">
    <% @account.expenses.each do |expense| %>
      <div class="event">
        <div class="label">
          <%= semantic_icon(expense.category.icon) %>
        </div>
        <div class="content">
          Expense worth P <%= expense.amount %> recorded. <br>
          Description: <%= expense.description %>
          <br><br>
          <div class="date"> <%= expense.created_at.strftime("%B %d, %Y") %></div>
        </div>
        <div class="meta">
          <a class="category">
            <b>Category</b>: <%= expense.category.name %>
          </a> | 
          <%= link_to 'Edit Expense', edit_account_expense_path(@account, expense) %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="ui bottom attached tab segment" data-tab="income">
  <div class="ui feed">
    <% @account.incomes.each do |income| %>
      <div class="event">
        <div class="label">
          <%= semantic_icon(income.category.icon) %>
        </div>
        <div class="content">
          Income worth P <%= income.amount %> recorded.<br>
          Description: <%= income.description %>
          <br><br>
          <div class="date"> <%= income.created_at.strftime("%B %d, %Y") %></div>
        </div>
        <div class="meta">
          <a class="category">
            <b>Category</b>: <%= income.category.name %>
          </a>| 
          <%= link_to 'Edit Income', edit_account_income_path(@account, income) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script>
  $(document).on('turbolinks:load', function(){
    $('.menu .item').tab();
  });
</script>